/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRegisterRouteImport } from './routes/UserRegister'
import { Route as SetProfileRouteImport } from './routes/SetProfile'
import { Route as ResetPasswordRouteImport } from './routes/ResetPassword'
import { Route as RegisterAdminRouteImport } from './routes/RegisterAdmin'
import { Route as RegisterRouteImport } from './routes/Register'
import { Route as ProfileRouteImport } from './routes/Profile'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as LandingRouteImport } from './routes/Landing'
import { Route as ForgotPasswordRouteImport } from './routes/ForgotPassword'
import { Route as IndexRouteImport } from './routes/index'

const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/UserRegister',
  path: '/UserRegister',
  getParentRoute: () => rootRouteImport,
} as any)
const SetProfileRoute = SetProfileRouteImport.update({
  id: '/SetProfile',
  path: '/SetProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/ResetPassword',
  path: '/ResetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAdminRoute = RegisterAdminRouteImport.update({
  id: '/RegisterAdmin',
  path: '/RegisterAdmin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/Profile',
  path: '/Profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/Landing',
  path: '/Landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/ForgotPassword',
  path: '/ForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ForgotPassword': typeof ForgotPasswordRoute
  '/Landing': typeof LandingRoute
  '/Login': typeof LoginRoute
  '/Profile': typeof ProfileRoute
  '/Register': typeof RegisterRoute
  '/RegisterAdmin': typeof RegisterAdminRoute
  '/ResetPassword': typeof ResetPasswordRoute
  '/SetProfile': typeof SetProfileRoute
  '/UserRegister': typeof UserRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ForgotPassword': typeof ForgotPasswordRoute
  '/Landing': typeof LandingRoute
  '/Login': typeof LoginRoute
  '/Profile': typeof ProfileRoute
  '/Register': typeof RegisterRoute
  '/RegisterAdmin': typeof RegisterAdminRoute
  '/ResetPassword': typeof ResetPasswordRoute
  '/SetProfile': typeof SetProfileRoute
  '/UserRegister': typeof UserRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ForgotPassword': typeof ForgotPasswordRoute
  '/Landing': typeof LandingRoute
  '/Login': typeof LoginRoute
  '/Profile': typeof ProfileRoute
  '/Register': typeof RegisterRoute
  '/RegisterAdmin': typeof RegisterAdminRoute
  '/ResetPassword': typeof ResetPasswordRoute
  '/SetProfile': typeof SetProfileRoute
  '/UserRegister': typeof UserRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ForgotPassword'
    | '/Landing'
    | '/Login'
    | '/Profile'
    | '/Register'
    | '/RegisterAdmin'
    | '/ResetPassword'
    | '/SetProfile'
    | '/UserRegister'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ForgotPassword'
    | '/Landing'
    | '/Login'
    | '/Profile'
    | '/Register'
    | '/RegisterAdmin'
    | '/ResetPassword'
    | '/SetProfile'
    | '/UserRegister'
  id:
    | '__root__'
    | '/'
    | '/ForgotPassword'
    | '/Landing'
    | '/Login'
    | '/Profile'
    | '/Register'
    | '/RegisterAdmin'
    | '/ResetPassword'
    | '/SetProfile'
    | '/UserRegister'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegisterAdminRoute: typeof RegisterAdminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetProfileRoute: typeof SetProfileRoute
  UserRegisterRoute: typeof UserRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/UserRegister': {
      id: '/UserRegister'
      path: '/UserRegister'
      fullPath: '/UserRegister'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SetProfile': {
      id: '/SetProfile'
      path: '/SetProfile'
      fullPath: '/SetProfile'
      preLoaderRoute: typeof SetProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ResetPassword': {
      id: '/ResetPassword'
      path: '/ResetPassword'
      fullPath: '/ResetPassword'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegisterAdmin': {
      id: '/RegisterAdmin'
      path: '/RegisterAdmin'
      fullPath: '/RegisterAdmin'
      preLoaderRoute: typeof RegisterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profile': {
      id: '/Profile'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Landing': {
      id: '/Landing'
      path: '/Landing'
      fullPath: '/Landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ForgotPassword': {
      id: '/ForgotPassword'
      path: '/ForgotPassword'
      fullPath: '/ForgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegisterAdminRoute: RegisterAdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetProfileRoute: SetProfileRoute,
  UserRegisterRoute: UserRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
